import type { Metadata } from "next";
import { StageShell } from "@/components/shells/StageShell";
import { WhatsAppCta } from "@/components/marketing/WhatsAppCta";
import { NearbyVenues } from "@/components/marketing/NearbyVenues";
import { getVenues } from "@/lib/data";

export const metadata: Metadata = {
  title: "Locations",
  description:
    "Sharwin Table Tennis Academy venues across Bengaluru — find the table nearest you, then message us for this week's classes there.",
};

// Fully static: the venue list is a checked-in file (content/academy.json),
// regenerated by scripts/export-content.mjs. What is ON at each venue this week
// is answered in the WhatsApp thread — the site carries no public timetable.
export const revalidate = 3600;

const BOOK_MESSAGE = "Hi! I'd like to book table tennis classes at one of your venues.";

export default async function LocationsPage() {
  const venues = await getVenues();

  return (
    <StageShell>
      <div className="mx-auto max-w-6xl px-6 pb-24 pt-28">
        <p className="label mb-3">Locations</p>
        <h1 className="font-display mb-4 text-4xl md:text-6xl">
          Pick your table
        </h1>
        <p className="mb-10 max-w-md text-lg text-smoke">
          Find the venue nearest you, then message us — we&apos;ll send you
          this week&apos;s classes there and hold you a place.
        </p>

        <NearbyVenues venues={venues} />

        {/* Closing CTA */}
        <div className="mt-16 rounded-[12px] border border-line bg-ink-2 p-8 text-center md:p-12">
          <h2 className="font-display text-3xl md:text-4xl">Ready to play?</h2>
          <p className="mx-auto mt-3 max-w-md text-smoke">
            Tell us your venue in one message — we&apos;ll send you this
            week&apos;s classes there and confirm your place in the thread.
          </p>
          <div className="mt-6 flex justify-center">
            <WhatsAppCta size="lg" message={BOOK_MESSAGE}>
              Book on WhatsApp
            </WhatsAppCta>
          </div>
        </div>
      </div>

      {/* Sticky bottom CTA — phones only */}
      <div className="pb-safe fixed inset-x-0 bottom-0 z-30 border-t border-line bg-ink/95 p-3 backdrop-blur sm:hidden">
        <WhatsAppCta className="w-full" message={BOOK_MESSAGE}>
          Book on WhatsApp
        </WhatsAppCta>
      </div>
    </StageShell>
  );
}
