-- Enable pgcrypto for UUID generation (Standard for Supabase)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- 0. ENUMS (Strict Type Definitions)
-- ==========================================
CREATE TYPE user_role AS ENUM ('client', 'coach', 'manager');
CREATE TYPE location_type AS ENUM ('public', 'private');
CREATE TYPE class_type AS ENUM ('group', 'private');
CREATE TYPE booking_status AS ENUM ('active', 'paused', 'cancelled');
CREATE TYPE day_code AS ENUM ('SU', 'MO', 'TU', 'WE', 'TH', 'FR', 'SA');

-- ==========================================
-- 1. PROFILES (The Users)
-- ==========================================
CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(20),
    role user_role DEFAULT 'client',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. COACHES (The Calendar Map)
-- ==========================================
CREATE TABLE coaches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
    bio TEXT,
    gcal_id VARCHAR(255) UNIQUE NOT NULL,
    color_code VARCHAR(7) DEFAULT '#' || lpad(to_hex(floor(random() * 16777215)::bigint)::text, 6, '0'),
    is_active BOOLEAN DEFAULT TRUE
);

-- ==========================================
-- 3. LOCATIONS (The Places)
-- ==========================================
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address TEXT NOT NULL,
    type location_type NOT NULL DEFAULT 'public',
    is_active BOOLEAN DEFAULT TRUE
);

-- ==========================================
-- 4. BATCHES (The Menu / Catalog)
-- ==========================================
CREATE TABLE batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    day_codes day_code[] NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    location_id BIGINT REFERENCES locations(id),
    default_coach_id BIGINT REFERENCES coaches(id),
    class_type class_type NOT NULL DEFAULT 'group',
    max_capacity INTEGER DEFAULT 10,
    is_active BOOLEAN DEFAULT TRUE
);

-- ==========================================
-- 5. BOOKINGS (The Contract)
-- ==========================================
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    batch_id BIGINT REFERENCES batches(id),
    status booking_status DEFAULT 'active',
    start_date DATE DEFAULT CURRENT_DATE,
    end_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 6. AUTOMATION (Triggers)
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 7. PERMISSIONS
-- ==========================================
GRANT ALL ON TABLE profiles TO authenticated;
GRANT ALL ON TABLE coaches TO authenticated;
GRANT ALL ON TABLE locations TO authenticated;
GRANT ALL ON TABLE batches TO authenticated;
GRANT ALL ON TABLE bookings TO authenticated;

GRANT ALL ON TABLE profiles TO service_role;
GRANT ALL ON TABLE coaches TO service_role;
GRANT ALL ON TABLE locations TO service_role;
GRANT ALL ON TABLE batches TO service_role;
GRANT ALL ON TABLE bookings TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
