-- 0072 — wa_messages gets a monotonic sequence, because created_at cannot
-- order a conversation.
--
-- Both rows of a turn (the user's message and the assistant's reply) are
-- written in ONE insert, so Postgres stamps them with an identical created_at:
-- now() is transaction-start time, not statement time. The agent's history
-- query broke that dead heat with `.order("id")` — and `id` is
-- gen_random_uuid(). A coin toss, on every turn.
--
-- Measured on live data before this migration: 139 of 314 tied pairs (44.3%)
-- loaded with the assistant's reply BEFORE the question that prompted it. The
-- history builder merges consecutive same-role rows, so a displaced user row
-- got glued to the next user message and handed back to the model as one live
-- instruction. That is how the message "Hi!" re-ran the previous turn's
-- create_group_class and created two real recurring classes
-- (classes.created_at 2026-08-09 04:33:27.767+00 and .088+00).
--
-- seq is bigint + backfill + identity, NOT `add column seq bigserial`. The
-- latter assigns values in physical heap order during the table rewrite, which
-- would bake today's scramble in permanently — the exact bug, frozen.

alter table public.wa_messages add column if not exists seq bigint;

-- Deterministic backfill. Ordering within a tied pair puts 'user' before
-- 'assistant' (a reply cannot precede its prompt), and id is the final
-- tiebreak purely so the result is reproducible.
with ordered as (
  select id,
         row_number() over (
           order by created_at,
                    case role when 'user' then 0 else 1 end,
                    id
         ) as rn
  from public.wa_messages
)
update public.wa_messages m
   set seq = ordered.rn
  from ordered
 where ordered.id = m.id
   and m.seq is null;

alter table public.wa_messages alter column seq set not null;

-- Attach an identity so future inserts number themselves, starting past the
-- backfill. Inserts that supply no seq get the next value; a multi-row insert
-- numbers its rows in the order they are written, which is what makes
-- `insert([user, assistant])` order correctly by construction.
alter table public.wa_messages
  alter column seq add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.wa_messages', 'seq'),
  coalesce((select max(seq) from public.wa_messages), 0) + 1,
  false
);

alter table public.wa_messages add constraint wa_messages_seq_key unique (seq);

-- The agent reads the tail of one conversation: (phone, seq desc) serves it
-- directly. The old (phone, created_at desc) index stays for time-range reads.
create index if not exists wa_messages_phone_seq_idx
  on public.wa_messages (phone, seq desc);
