revoke execute on function public._assert_private_plan_allows(p_client uuid, p_start timestamp with time zone, p_duration integer) from public, anon;
revoke execute on function public._book_one(p_session uuid, p_client uuid, p_player uuid, p_series uuid, p_notify boolean) from public, anon;
revoke execute on function public._consume_group_credit(p_client uuid, p_player uuid) from public, anon;
drop function public._create_private_occurrence(p_client uuid, p_player uuid, p_start timestamp with time zone, p_duration integer, p_address text, p_postcode text, p_lat double precision, p_lng double precision, p_has_table boolean, p_access_notes text, p_address_details jsonb, p_preferred uuid, p_series uuid, p_notify boolean);
revoke execute on function public._create_private_occurrence(p_client uuid, p_player uuid, p_start timestamp with time zone, p_duration integer, p_address text, p_postcode text, p_lat double precision, p_lng double precision, p_has_table boolean, p_access_notes text, p_address_details jsonb, p_preferred uuid, p_series uuid, p_notify boolean, p_venue_id uuid, p_venue_label text, p_unit_label text) from public, anon;
revoke execute on function public._delete_class_on_private_details_delete() from public, anon;
revoke execute on function public._session_alert_resolve_trigger() from public, anon;
revoke execute on function public.add_school_player(p_session uuid, p_full_name text, p_grade smallint) from public, anon;
revoke execute on function public.assign_coach(p_session uuid, p_preferred uuid) from public, anon;
revoke execute on function public.assign_unassigned_sessions() from public, anon;
revoke execute on function public.book_series(p_session uuid, p_player uuid, p_recurring boolean) from public, anon;
revoke execute on function public.book_session(p_session uuid, p_player uuid) from public, anon;
revoke execute on function public.cancel_booking(p_booking uuid) from public, anon;
revoke execute on function public.cancel_private_series(p_series uuid) from public, anon;
revoke execute on function public.cancel_series(p_series uuid) from public, anon;
revoke execute on function public.claim_client_invite() from public, anon;
revoke execute on function public.claim_coach_invite_by_phone(p_user uuid, p_phone text) from public, anon;
revoke execute on function public.claim_coach_invite_on_signup() from public, anon;
revoke execute on function public.claim_cover_session(p_session uuid) from public, anon;
revoke execute on function public.claim_waitlist_spot(p_booking uuid) from public, anon;
revoke execute on function public.coach_confirm_session(p_session uuid) from public, anon;
revoke execute on function public.coach_filter_failure(p_coach uuid, p_session uuid) from public, anon;
revoke execute on function public.coach_has_client(p_client uuid) from public, anon;
revoke execute on function public.coach_mark_arrival(p_session uuid, p_late boolean, p_source text) from public, anon;
revoke execute on function public.coach_school_venues() from public, anon;
revoke execute on function public.coach_undo_arrival(p_session uuid) from public, anon;
revoke execute on function public.create_private_series(payload jsonb) from public, anon;
revoke execute on function public.expire_credits() from public, anon;
revoke execute on function public.founder_reassign(p_session uuid, p_coach uuid, p_lock boolean, p_force boolean) from public, anon;
revoke execute on function public.generate_class_sessions(p_weeks integer) from public, anon;
revoke execute on function public.generate_private_sessions(p_weeks integer) from public, anon;
revoke execute on function public.get_bookable_slots(p_lat double precision, p_lng double precision, p_duration integer, p_player uuid, p_days integer) from public, anon;
revoke execute on function public.get_coach_wrapup_queue(p_coach uuid) from public, anon;
revoke execute on function public.get_pending_assessments(p_coach uuid) from public, anon;
revoke execute on function public.get_player_notes(p_player uuid) from public, anon;
revoke execute on function public.get_players_mastery(p_players uuid[]) from public, anon;
revoke execute on function public.get_setting_int(p_key text, p_default integer) from public, anon;
revoke execute on function public.grant_signup_trial() from public, anon;
revoke execute on function public.handle_coach_dropout(p_coach uuid, p_from timestamp with time zone, p_to timestamp with time zone) from public, anon;
revoke execute on function public.handle_new_user() from public, anon;
revoke execute on function public.has_active_subscription(p_client uuid) from public, anon;
revoke execute on function public.has_group_subscription(p_client uuid) from public, anon;
revoke execute on function public.is_approved() from public, anon;
revoke execute on function public.notify_founders(p_type text, p_title text, p_body text, p_data jsonb) from public, anon;
revoke execute on function public.notify_name_the_session() from public, anon;
revoke execute on function public.offer_cover_session(p_session uuid) from public, anon;
revoke execute on function public.ops_notify_assessment() from public, anon;
revoke execute on function public.ops_notify_booking_created() from public, anon;
revoke execute on function public.ops_notify_booking_status() from public, anon;
revoke execute on function public.ops_notify_class_open() from public, anon;
revoke execute on function public.ops_notify_coach_change() from public, anon;
revoke execute on function public.ops_notify_credit_used() from public, anon;
revoke execute on function public.ops_notify_invoice() from public, anon;
revoke execute on function public.ops_notify_new_player() from public, anon;
revoke execute on function public.ops_notify_new_profile() from public, anon;
revoke execute on function public.ops_notify_order_paid() from public, anon;
revoke execute on function public.ops_notify_student_note() from public, anon;
revoke execute on function public.ops_notify_subscription() from public, anon;
revoke execute on function public.private_minutes_balance(p_client uuid) from public, anon;
revoke execute on function public.private_plan_limits(p_client uuid) from public, anon;
revoke execute on function public.prune_wa_inbound_seen() from public, anon;
revoke execute on function public.queue_coach_changed(p_user uuid, p_session uuid, p_title text, p_body text, p_url text) from public, anon;
revoke execute on function public.rank_coaches(p_session uuid, p_preferred uuid) from public, anon;
revoke execute on function public.request_private_class(payload jsonb) from public, anon;
revoke execute on function public.reschedule_booking(p_booking uuid, p_target_session uuid) from public, anon;
revoke execute on function public.reschedule_private_session(p_session uuid, p_new_start timestamp with time zone, p_confirm boolean) from public, anon;
revoke execute on function public.reschedule_series(p_booking uuid, p_target_session uuid) from public, anon;
revoke execute on function public.reset_session_confirmation() from public, anon;
revoke execute on function public.review_signup_request(p_client uuid, p_approve boolean, p_reviewer uuid) from public, anon;
revoke execute on function public.save_session_assessment(p_player uuid, p_session uuid, p_ratings jsonb, p_coach uuid) from public, anon;
revoke execute on function public.school_has_player(p_player uuid) from public, anon;
revoke execute on function public.session_label(p_session uuid) from public, anon;
revoke execute on function public.submit_signup_request(p_name text, p_phone text) from public, anon;
